# Optimized for security-focused full-stack development
have_fun: false  # Keep it professional and precise
code_review:
  disable: false
  comment_severity_threshold: LOW  # Catch everything - you nitpick, so should Gemini
  max_review_comments: -1  # Unlimited - thorough reviews matter
  pull_request_opened:
    help: false  # You don't need basic help messages
    summary: true
    code_review: true
    include_drafts: true  # Review early, review often

# Ignore common patterns for your stack
ignore_patterns:
  - "**/node_modules/**"
  - "**/.venv/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/dist/**"
  - "**/build/**"
  - "**/.pytest_cache/**"
  - "**/venv/**"
  - "**/.env"
  - "**/*.log"
